version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - app
    ports:
      - 80:80
      - 433:443

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    volumes:
      - .:/var/app:rw,cached
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}

  vault:
    image: vault:latest
    volumes:
      - ./docker/vault/config:/vault/config
      - ./docker/vault/policies:/vault/policies
      - ./docker/vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_API_ADDR=${VAULT_API_ADDR}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json