version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - app
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./app/:/app/
    env_file:
      - ./docker/environment.yml
      - ./docker/environment.development.yml

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.development
      target: development
    container_name: app
    volumes:
      - .:/app
    env_file:
      - ./docker/environment.yml
      - ./docker/environment.development.yml

#  vault:
#    image: vault:latest
#    volumes:
#      - ./docker/vault/config:/vault/config
#      - ./docker/vault/policies:/vault/policies
#      - ./docker/vault/data:/vault/data
#    ports:
#      - 8200:8200
#    environment:
#      - VAULT_ADDR
#      - VAULT_API_ADDR
#      - VAULT_ADDRESS
#    cap_add:
#      - IPC_LOCK
#    command: vault server -config=/vault/config/vault.json

# blackfire:
#   image: blackfire/blackfire
#   environment:
#     # Exposes BLACKFIRE_SERVER_* environment variables from the host
#     - BLACKFIRE_SERVER_ID
#     - BLACKFIRE_SERVER_TOKEN
