version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - app
    ports:
      - 8080:80
      - 4433:443

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    volumes:
      - .:/var/app:rw,cached
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
