version: "3.7"

#volumes:
#  postgresql-persistence:
#  redis-persistence:
#  rabbitmq-persistence:
#  cba-frontend-data:

networks:
  external-tier:
    driver: bridge
  app-tier:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: development
    volumes:
      - .:/var/app
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    environment:
      - APP_ENV
      - APP_DEBUG
      - APP_SECRET
    networks:
      - app-tier
      - external-tier

  # app_worker:
  # ...

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: development
      args:
        APP_DEBUG: "1"
        APP_ENV: "dev"
    volumes:
      - .:/var/app
    networks:
      - app-tier

  vault:
    image: vault:latest
    container_name: vault
    volumes:
      - ./docker/vault/config:/vault/config
      - ./docker/vault/policies:/vault/policies
      - ./docker/vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR
      - VAULT_API_ADDR
      - VAULT_ADDRESS
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    networks:
      - app-tier
