version: "3.7"

services:
  nginx:
    image: soprun/ddd-project-nginx:latest
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    # env_file:
    #   - ./docker/environment.yml
    #   - ./docker/environment.development.yml

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: development
      args:
        APP_DEBUG: "1"
        APP_ENV: "dev"
    container_name: app
    volumes:
      - .:/var/app
    # env_file:
    #   - ./docker/environment.yml
    #   - ./docker/environment.development.yml

  vault:
    image: vault:latest
    volumes:
      - ./docker/vault/config:/vault/config
      - ./docker/vault/policies:/vault/policies
      - ./docker/vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR
      - VAULT_API_ADDR
      - VAULT_ADDRESS
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
