version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    command: [nginx-debug, '-g', 'daemon off;']
    container_name: nginx
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    volumes:
      - .:/var/app:rw,cached
