version: "3.7"

services:
  nginx:
    image: soprun/ddd-project-nginx:latest
    env_file:
      - ./docker/environment.yml
      - ./docker/environment.production.yml

  app:
    image: soprun/ddd-project-app:latest
    env_file:
      - ./docker/environment.yml
      - ./docker/environment.production.yml

