name: Build application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building applications on PHP 7.4
    steps:
      - uses: actions/checkout@v2

      # see https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          php-version: 7.4
          coverage: none # disable xdebug, pcov
          tools: phpunit

      - name: Check that platform requirements are satisfied.
        run: composer check-platform-reqs

      - name: Validates a composer.json and composer.lock.
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest
        # run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Compiles .env files to .env.local.php.
        run: composer symfony:dump-env prod

      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: .env.local.php

      - name: Installs bundles web assets under a public directory
        run: php bin/console assets:install

      - name: Put built assets in artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: public

      - name: Run Unit Tests
        run: phpunit

      - name: Put built code coverage results in artifacts
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: build/logs/clover.xml
#
#  unit_tests:
#    needs: build
#    runs-on: ubuntu-latest
#    name: Unit Tests
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        env:
#          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          php-version: 7.4
#          coverage: none
#
#      - name: Run Unit Tests
#        run: vendor/bin/phpunit
#
#      - name: Archive code coverage results
#        uses: actions/upload-artifact@v1
#        with:
#          name: code-coverage-report
#          path: build/logs/clover.xml

#  phpstan-analysis:
#    needs: build
#    runs-on: ubuntu-latest
#    name: PHPStan static code analysis
#    steps:
#      - uses: actions/checkout@v2
#
#      # see https://github.com/shivammathur/setup-php
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 7.4
#          coverage: none # disable xdebug, pcov
#          tools: cs2pr, phpstan
#
#      - name: Run PHPStan
#        run: phpstan analyse src --error-format=checkstyle | cs2pr
