name: Build application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  APP_URL: ${{ secrets.APP_URL }}
  APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
  APP_SECRET: ${{ secrets.APP_SECRET }}
  APP_RELEASE: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Building applications
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2

      # required for "git tag" presence for monorepo-builder split and changelog-linker git tags resolver; default is 1
      # https://github.com/actions/checkout#fetch-all-tags
      # - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      # see https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, bcmath # Setup any required extensions for tests
          coverage: xdebug # disable xdebug, pcov
          tools: cs2pr, phpstan

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --dev --no-interaction

      - name: Run static code analysis
        run: phpstan analyse src --error-format=checkstyle | cs2pr

      - name: Run Unit Tests
        run: php bin/phpunit --coverage-clover build/logs/clover.xml

      # TODO: Move to Docker global dependencies.
      - name: Run PHP Coveralls
        run: php vendor/bin/php-coveralls --verbose
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  check_composer:
    runs-on: ubuntu-latest
    name: Check Composer
    steps:
      - uses: actions/checkout@v2

      - name: Check that platform requirements are satisfied.
        run: composer check-platform-reqs

      - name: Validates a composer.json and composer.lock.
        run: composer validate
