name: Docker Image CI

on:
  push:
    branches:
      - master
    paths:
      - './docker/*'
      - './docker-compose.production.yml'
      - './docker-compose.yml'

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build app image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true
          repository: soprun/ddd-project-app
          tags: latest
          dockerfile: ./docker/app/Dockerfile

  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build nginx image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          tag_with_sha: true
          repository: soprun/ddd-project-nginx
          tags: latest
          dockerfile: ./docker/nginx/Dockerfile
