name: Build application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    needs: phpstan-analysis
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }} Test
    strategy:
      matrix:
        php: ['7.4', '8.0']
    steps:
      - uses: actions/checkout@v2

      # see https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: pcov
          tools: php-cs-fixer, phpunit, cs2pr, phpstan

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
      #
      # - name: Run Unit Tests
      #   run: phpunit
      #
      # - name: Run check Coding Standard
      #   run: php ci/check_coding_standard_readme_sync.php
      #
      #      - name: Archive production artifacts
      #        uses: actions/upload-artifact@v1
      #        with:
      #          name: dist
      #          path: dist
      #
      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: code-coverage-report
      #     path: build/logs/clover.xml

  phpstan-analysis:
    runs-on: ubuntu-latest
    name: PHPStan static code analysis
    steps:
      - uses: actions/checkout@v2

      # see https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none # disable xdebug, pcov
          tools: cs2pr, phpstan

      - name: Run PHPStan
        run: phpstan analyse src --error-format=checkstyle | cs2pr
